### ISSUE TITLE
Feature request: Julia kernel to jupyter 

### ISSUE THREAD

**Issue by guidov** [ucphhpc/nbi-jupyter-docker-stacks#48]
Hi, 

I would be great if we had an docker image with access to a Julia kernel on ERDA, using IJulia.

https://juliapackages.com/p/ijulia

Thanks

**Comment by rasmunk** [comment]
Hi @guidov,

Thank you for this feature request, Julia would certainly be a good candidate for a Notebook:))
I will look into when there is time for it!

Regards
Rasmus

**Comment by SebastianPrehn** [comment]
Hi @guidov,

I am currently developing a notebook using Julia for ERDA (#61), and if still relevant to you, I was curious what sort of packages you would use in Julia so that I could test them and add them.

**Comment by guidov** [comment]
Hi Sebastian, yes great , I saw you had been working on this.  I'll have to
get back to you later today. But some of the differential equation packages
are useful , plus I want to use speedweather.jl in a class in block4.

Guido

**Comment by guidov** [comment]
Hi , 
I don't know how many people will use this kernel, but I could see using:
https://docs.sciml.ai/DiffEqDocs/stable/
https://github.com/SpeedyWeather/SpeedyWeather.jl

Also I'm sure students and others might use in the future the ML ecosystem that is available:
https://docs.sciml.ai/Overview/stable/overview/#overview

and the top packages from here:
https://juliapackages.com/c/machine-learning

But don't worry too much about putting in a lot if it is too much work. Better not to waste too much time on this.
Thanks

**Comment by SebastianPrehn** [comment]
As of 70a43550670e7209a3c74268003a3c63ab4c0ed9, Julia 1.10.0 is in Jupyter Notebook on DAG with most of the packages you've mentioned 🎉 I'm also in the process of adding an additional notebook aimed at Julia, with more attention paid to the machine learning packages #62
